//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationLog
    {
        public long Id { get; set; }
        public double FirstValue { get; set; }
        public double SecondValue { get; set; }
        public string Operation { get; set; }
        public string UserUrl { get; set; }
        public System.DateTime TimeStamp { get; set; }
    }
}
